name: Deployment pipeline

on:
  push:
    branches:
      - main

jobs:
  simple_deployment_pipeline:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Install ESLint
        run: npm install eslint @eslint/js --save-dev 

      - name: Create ESLint configuration
        run: |
          echo "module.exports = {
              env: {
                  browser: true,
                  es2021: true,
              },
              extends: [
                  'eslint:recommended',
                  'plugin:react/recommended',
              ],
              parserOptions: {
                  ecmaVersion: 12,
                  sourceType: 'module',
              },
              settings: {
                  react: {
                      version: 'detect', // Automatically detect the React version
                  },
              },
              rules: {
                  // Define any custom rules here
                  'react/prop-types': 'warn', // Change to 'error' to enforce prop validation
              },
          };" > .eslintrc.js

      - name: Check style
        run: npm run eslint

